title: Jordan Antonio
logo: /assets/images/1744742620161.jpg 
description: >
  ğŸ“ San Angelo, TX  \n
  ğŸ“§ jordan.antonio7058@gmail.com  \n
  ğŸ“ 702-273-7058  \n
  LinkedIn: https://www.linkedin.com/in/jordanantonio/
show_downloads: true
theme: jekyll-theme-minimal
