title: Jordan Antonio
logo: /1744742620161.jpg
description: ğŸ“ San Angelo, TX  
ğŸ“§ jordan.antonio7058@gmail.com  
ğŸ“ 702-273-7058  
[LinkedIn](https://www.linkedin.com/in/jordanantonio/)
show_downloads: true
theme: jekyll-theme-minimal
